// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUGiBXtpWmW183f14pS8aZlJRemQB2D0',
    appId: '1:903741518580:web:a802f0933932551fc0e4a1',
    messagingSenderId: '903741518580',
    projectId: 'sn-silos1',
    authDomain: 'sn-silos1.firebaseapp.com',
    storageBucket: 'sn-silos1.appspot.com',
    measurementId: 'G-GVL4WMP3T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HxbLrdgMMAr6GtC2VVAkBS-SgrqhWbc',
    appId: '1:903741518580:android:06f60b2947a7cbcec0e4a1',
    messagingSenderId: '903741518580',
    projectId: 'sn-silos1',
    storageBucket: 'sn-silos1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-xqH7FKd1HNtin7sgLjsM_-5285jP9Q',
    appId: '1:903741518580:ios:d29bd38c43a4384ec0e4a1',
    messagingSenderId: '903741518580',
    projectId: 'sn-silos1',
    storageBucket: 'sn-silos1.appspot.com',
    iosClientId: '903741518580-jlrned7i0d26miga79va97u7ouipofu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.snSilos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-xqH7FKd1HNtin7sgLjsM_-5285jP9Q',
    appId: '1:903741518580:ios:42fc1c1354223a49c0e4a1',
    messagingSenderId: '903741518580',
    projectId: 'sn-silos1',
    storageBucket: 'sn-silos1.appspot.com',
    iosClientId: '903741518580-6u4n1qmcruvkh3eet724re2qkhhnsl96.apps.googleusercontent.com',
    iosBundleId: 'com.example.snSilos.RunnerTests',
  );
}
